services:
  hikemoms:
    build: .
    container_name: hikemoms
    restart: unless-stopped
    volumes:
      - hikemoms-data:/app/data
    labels:
      - "traefik.http.services.hikemoms.loadbalancer.server.port=3000"
    networks:
      - traefik-proxy

volumes:
  hikemoms-data:

networks:
  traefik-proxy:
    external: true
