services:
  hikes:
    build: .
    container_name: hikes
    restart: unless-stopped
    volumes:
      - hikes-data:/app/data
    labels:
      - "traefik.http.services.hikes.loadbalancer.server.port=3000"
    networks:
      - traefik-proxy

volumes:
  hikes-data:

networks:
  traefik-proxy:
    external: true
